---
# Base Kargo Project - Generic template
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-quickstart-template
  namespace: kargo-quickstart-template
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
