apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Team-specific namespace - this will be overridden by each team's branch
namespace: kargo-quickstart-template-team-alpha

# Add team prefix to all resource names
namePrefix: kargo-quickstart-template-team-alpha-

resources:
- project.yaml
- warehouse.yaml
- verification-job.yaml
- stages.yaml
- rbac.yaml

# Transform all resources to use team-specific namespace
patches:
- target:
    kind: Project
  patch: |-
    - op: replace
      path: /metadata/name
      value: kargo-quickstart-template-team-alpha

- target:
    kind: Warehouse
  patch: |-
    - op: replace
      path: /metadata/name
      value: kargo-quickstart-template-team-alpha
    - op: replace
      path: /spec/subscriptions/1/git/branch
      value: team-alpha-dev

- target:
    kind: AnalysisTemplate
  patch: |-
    - op: replace
      path: /metadata/name
      value: verify-deployment-health-team-alpha

- target:
    kind: Stage
  patch: |-
    - op: replace
      path: /spec/requestedFreight/0/origin/name
      value: kargo-quickstart-template-team-alpha
    - op: replace
      path: /spec/promotionTemplate/spec/steps/0/config/checkout/0/branch
      value: team-alpha-dev

commonLabels:
  team: alpha
