---
# Base Kargo RBAC Configuration - Generic template
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admin
  namespace: kargo-quickstart-template
rules:
- apiGroups: ["kargo.akuity.io"]
  resources: ["stages", "promotions", "freights", "warehouses"]
  verbs: ["*"]
- apiGroups: ["argoproj.io"]
  resources: ["analysisruns", "analysistemplates"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["secrets", "serviceaccounts", "events"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
  namespace: kargo-quickstart-template
rules:
- apiGroups: ["kargo.akuity.io"]
  resources: ["stages", "promotions", "freights"]
  verbs: ["get", "list", "watch", "promote"]
- apiGroups: ["argoproj.io"]
  resources: ["analysisruns", "analysistemplates"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: viewer
  namespace: kargo-quickstart-template
rules:
- apiGroups: ["kargo.akuity.io"]
  resources: ["stages", "promotions", "freights", "warehouses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["argoproj.io"]
  resources: ["analysisruns", "analysistemplates"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin
  namespace: kargo-quickstart-template
  annotations:
    rbac.kargo.akuity.io/claim.email: "admin@example.com"
    rbac.kargo.akuity.io/claim.groups: "admin"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer
  namespace: kargo-quickstart-template
  annotations:
    rbac.kargo.akuity.io/claim.email: "developer@example.com"
    rbac.kargo.akuity.io/claim.groups: "developers"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: viewer
  namespace: kargo-quickstart-template
  annotations:
    rbac.kargo.akuity.io/claim.email: "viewer@example.com"
    rbac.kargo.akuity.io/claim.groups: "viewers"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-binding
  namespace: kargo-quickstart-template
subjects:
- kind: ServiceAccount
  name: admin
  namespace: kargo-quickstart-template
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-binding
  namespace: kargo-quickstart-template
subjects:
- kind: ServiceAccount
  name: developer
  namespace: kargo-quickstart-template
roleRef:
  kind: Role
  name: developer
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: viewer-binding
  namespace: kargo-quickstart-template
subjects:
- kind: ServiceAccount
  name: viewer
  namespace: kargo-quickstart-template
roleRef:
  kind: Role
  name: viewer
  apiGroup: rbac.authorization.k8s.io