---
# Dev stage - Team Beta specific
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-quickstart-template-team-beta
  labels:
    team: beta
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-quickstart-template-team-beta
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/csz-ghorg/kargo-quickstart-template.git
      - name: imageRepo
        value: ghcr.io/csz-akuity/guestbook
      steps:
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitRepo }}
          checkout:
          - branch: team-beta-dev
            path: ./src
          - branch: env/dev
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/app/env/dev
          images:
          - image: ${{ vars.imageRepo }}
            tag: ${{ imageFrom(vars.imageRepo).Tag }}
      - uses: kustomize-build
        config:
          path: ./src/app/env/dev
          outPath: ./out/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          message: ${{ outputs['update-image'].commitMessage }}
      - uses: git-push
        config:
          path: ./out
          targetBranch: env/dev
      - uses: argocd-update
        config:
          apps:
          - name: kargo-quickstart-template-dev-team-beta
            sources:
            - repoURL: ${{ vars.gitRepo }}
              desiredRevision: ${{ outputs.commit.commit }}
---
# Staging stage - Team Beta specific
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: kargo-quickstart-template-team-beta
  labels:
    team: beta
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-quickstart-template-team-beta
    sources:
      stages:
      - dev
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/csz-ghorg/kargo-quickstart-template.git
      - name: imageRepo
        value: ghcr.io/csz-akuity/guestbook
      steps:
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitRepo }}
          checkout:
          - branch: team-beta-dev
            path: ./src
          - branch: env/staging
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/app/env/staging
          images:
          - image: ${{ vars.imageRepo }}
            tag: ${{ imageFrom(vars.imageRepo).Tag }}
      - uses: kustomize-build
        config:
          path: ./src/app/env/staging
          outPath: ./out/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          message: ${{ outputs['update-image'].commitMessage }}
      - uses: git-push
        config:
          path: ./out
          targetBranch: env/staging
      - uses: argocd-update
        config:
          apps:
          - name: kargo-quickstart-template-staging-team-beta
            sources:
            - repoURL: ${{ vars.gitRepo }}
              desiredRevision: ${{ outputs.commit.commit }}
---
# Production stage - Team Beta specific
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-quickstart-template-team-beta
  labels:
    team: beta
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-quickstart-template-team-beta
    sources:
      stages:
      - staging
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/csz-ghorg/kargo-quickstart-template.git
      - name: imageRepo
        value: ghcr.io/csz-akuity/guestbook
      steps:
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitRepo }}
          checkout:
          - branch: team-beta-dev
            path: ./src
          - branch: env/prod
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/app/env/prod
          images:
          - image: ${{ vars.imageRepo }}
            tag: ${{ imageFrom(vars.imageRepo).Tag }}
      - uses: kustomize-build
        config:
          path: ./src/app/env/prod
          outPath: ./out/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          message: ${{ outputs['update-image'].commitMessage }}
      - uses: git-push
        config:
          path: ./out
          targetBranch: env/prod
      - uses: argocd-update
        config:
          apps:
          - name: kargo-quickstart-template-prod-team-beta
            sources:
            - repoURL: ${{ vars.gitRepo }}
              desiredRevision: ${{ outputs.commit.commit }}