apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kargo-quickstart-template-team-beta
namePrefix: kargo-quickstart-template-team-beta-

resources:
- ../base

patchesStrategicMerge:
- |-
  apiVersion: kargo.akuity.io/v1alpha1
  kind: Project
  metadata:
    name: kargo-quickstart-template-team-beta
  spec: {}

patches:
- target:
    kind: Warehouse
  patch: |-
    - op: replace
      path: /metadata/name
      value: kargo-quickstart-template-team-beta
    - op: replace
      path: /spec/subscriptions/1/git/branch
      value: team-beta-dev

- target:
    kind: AnalysisTemplate
  patch: |-
    - op: replace
      path: /metadata/name
      value: verify-deployment-health-team-beta

commonLabels:
  team: beta
